
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/winterme/spring-cloud-config-yml
          username: xxx
          password: xxx
          skip-ssl-validation: true

server:
  port: 8888
  servlet:
    context-path: /config